<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="../form/top.jsp"%>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<style type="text/css">
	.btn-primary{
		background:#4e266d
	}
</body>
</html>
</style>
</head>
<body>
	<h1>공지사항</h1>
	 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	<table class="table table-striped table-hover" >
  		<thead>
  			<tr>
  				<th>번호</th>
  				<th>구분</th>
  				<th>제목</th>
  				<th>작성자</th>
  				<th>작성일</th>
  				<th>첨부파일</th>
  				<th>조회수</th>
  			</tr>
  		</thead>
  		<tbody>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  			<tr>
	  			<td>1</td>
	  			<td>2</td>
	  			<td>3</td>
	  			<td>4</td>
	  			<td>5</td>
	  			<td>6</td>
	  			<td>7</td>
  			</tr>
  		</tbody>
	</table>
<button class="btn-primary" type="submit">글쓰기</button>
</body>
<%@ include file = "../form/bottom.jsp" %>